#!/usr/bin/env python3
# coding: utf-8

from __future__ import print_function
from __future__ import unicode_literals
import os
import subprocess
import sys
from gitlab_helpers import success_msg, fail_msg
import configparser
import os

def main(test_list):
    """
    Loop through each test and run them, add display results at the end

    If the test has a .py extension, import as a list and call main function

    :param list test_list: list of lists containing commands to run
    :return: highest error code
    """
    args = sys.argv[1:]
    results = []
    for test in test_list:
        # keep backward compatibility with version as an argument
        print("======== Testing %s ========" % test[0])
        test_w_args = test + args
        test_file = test_w_args[0]
        if test_file.endswith(".py"):
            test_lib = test_file[:-3]
            try:
                res = __import__(test_lib).main(argv=test_w_args)
            except Exception as e:
                print(e)
                res = 1
        else:
            res = subprocess.call(test_w_args)
        results.append(res)

    print()
    print("+" + "="*39)
    print("|  Tests summary:")
    print("|" + "-"*39)
    for test, error in zip(test_list, results):
        outcome = fail_msg if error else success_msg
        print("| {0:<28}{1}".format(test[0], outcome))
    print("+" + "="*39)
    return max(results)


if __name__ == '__main__':

    config = configparser.ConfigParser()
    config.read('env.INI', encoding='utf-8')
    env_data=config['env']
    
    lint_check_disabled = env_data.get('LINT_CHECK') == '0'
    lint_check_enabled = env_data.get('LINT_CHECK') == '1'
    tests_enabled = env_data.get('TESTS')
    tests_unspecified = env_data.get('TESTS') is None

    os.environ['VERSION']=env_data['VERSION']
    os.environ['CI_PROJECT_DIR']=env_data['CI_PROJECT_DIR']
    
    # Test list. Each test is a list with command + arguments.
    tests = []
    if not lint_check_disabled:
        tests.append(['test_flake8'])
        tests.append(['test_pylint'])

    if tests_unspecified and not lint_check_enabled:
        tests.append(['test_server.py'])

    elif tests_enabled:
        tests.append(['test_server.py'])

    if tests:
        exit(main(tests))
